---
- name: Add Elasticsearch GPG key.
  rpm_key:
    key: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository.
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0644

- name: Install Elasticsearch.
  yum: pkg=elasticsearch state=installed

- name: Create user elasticsearch
  user:
    name: elasticsearch
    uid: 1000
    group: root
    createhome: no
  
- name: Create directories
  file:
    path: "{{ item }}" 
    state: directory
    owner: elasticsearch 
    group: root
    mode: 0775
  with_items:
    - "{{ elasticsearch_config }}"
    - "{{ elasticsearch_config }}/scripts"
    - "{{ elasticsearch_data }}"
    - "{{ elasticsearch_logs }}"

- name: Stat config/elasticsearch.yml
  stat:
    path: "{{ elasticsearch_config }}/elasticsearch.yml"
  register: stat_output

- name: Template elasticsearch.yml
  template:
    src: "{{ item }}.j2"
    dest: "{{ elasticsearch_config }}/{{ item }}"
    group: root
    owner: elasticsearch
    mode: 0750
  with_items:
    - elasticsearch.yml
  when: not stat_output.stat.exists

- name: Stat config/logging.yml
  stat:
    path: "{{ elasticsearch_config }}/logging.yml"
  register: stat_output

- name: Template logging.yml 
  template:
    src: "{{ item }}.j2"
    dest: "{{ elasticsearch_config }}/{{ item }}"
    group: root
    owner: elasticsearch
    mode: 0750
  with_items:
    - logging.yml
  when: not stat_output.stat.exists

